### ISSUE TITLE
Validate email address

### ISSUE THREAD

**Issue by omaralsayed** [MakeUC/makeuc.io#44]
Only allow valid emails to be submitted on the registration form (currently accepts any string)

Perhaps `/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/` ?

**Comment by devagrawal09** [comment]
Done
